/// Flutter icons SGS_CustomIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SGS_CustomIcon
///      fonts:
///       - asset: fonts/SGS_CustomIcon.ttf
///
/// 
/// * Meteocons, Copyright (C) 2012 by Alessio Atzeni
///         Author:    Alessio Atzeni
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.alessioatzeni.com
/// * Font Awesome, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class SGSCustomIcon {
  SGSCustomIcon._();

  static const _kFontFam = 'SGS_CustomIcon';
  static const _kFontPkg = null;

  static const IconData sunrise = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniF02E = IconData(0xf02e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniF03C = IconData(0xf03c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniF046 = IconData(0xf046, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniF047 = IconData(0xf047, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniF051 = IconData(0xf051, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniF052 = IconData(0xf052, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniF055 = IconData(0xf055, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniF06E = IconData(0xf06e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniF078 = IconData(0xf078, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData uniF079 = IconData(0xf079, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apple = IconData(0xf179, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
